const stateFlagsData: { [key: string]: string } = {
  'Alabama': 'https://flagcdn.com/w80/us-al.png',
  'Alaska': 'https://flagcdn.com/w80/us-ak.png',
  'Arizona': 'https://flagcdn.com/w80/us-az.png',
  'Arkansas': 'https://flagcdn.com/w80/us-ar.png',
  'California': 'https://flagcdn.com/w80/us-ca.png',
  'Colorado': 'https://flagcdn.com/w80/us-co.png',
  'Connecticut': 'https://flagcdn.com/w80/us-ct.png',
  'Delaware': 'https://flagcdn.com/w80/us-de.png',
  'Florida': 'https://flagcdn.com/w80/us-fl.png',
  'Georgia': 'https://flagcdn.com/w80/us-ga.png',
  'Hawaii': 'https://flagcdn.com/w80/us-hi.png',
  'Idaho': 'https://flagcdn.com/w80/us-id.png',
  'Illinois': 'https://flagcdn.com/w80/us-il.png',
  'Indiana': 'https://flagcdn.com/w80/us-in.png',
  'Iowa': 'https://flagcdn.com/w80/us-ia.png',
  'Kansas': 'https://flagcdn.com/w80/us-ks.png',
  'Kentucky': 'https://flagcdn.com/w80/us-ky.png',
  'Louisiana': 'https://flagcdn.com/w80/us-la.png',
  'Maine': 'https://flagcdn.com/w80/us-me.png',
  'Maryland': 'https://flagcdn.com/w80/us-md.png',
  'Massachusetts': 'https://flagcdn.com/w80/us-ma.png',
  'Michigan': 'https://flagcdn.com/w80/us-mi.png',
  'Minnesota': 'https://flagcdn.com/w80/us-mn.png',
  'Mississippi': 'https://flagcdn.com/w80/us-ms.png',
  'Missouri': 'https://flagcdn.com/w80/us-mo.png',
  'Montana': 'https://flagcdn.com/w80/us-mt.png',
  'Nebraska': 'https://flagcdn.com/w80/us-ne.png',
  'Nevada': 'https://flagcdn.com/w80/us-nv.png',
  'New Hampshire': 'https://flagcdn.com/w80/us-nh.png',
  'New Jersey': 'https://flagcdn.com/w80/us-nj.png',
  'New Mexico': 'https://flagcdn.com/w80/us-nm.png',
  'New York': 'https://flagcdn.com/w80/us-ny.png',
  'North Carolina': 'https://flagcdn.com/w80/us-nc.png',
  'North Dakota': 'https://flagcdn.com/w80/us-nd.png',
  'Ohio': 'https://flagcdn.com/w80/us-oh.png',
  'Oklahoma': 'https://flagcdn.com/w80/us-ok.png',
  'Oregon': 'https://flagcdn.com/w80/us-or.png',
  'Pennsylvania': 'https://flagcdn.com/w80/us-pa.png',
  'Rhode Island': 'https://flagcdn.com/w80/us-ri.png',
  'South Carolina': 'https://flagcdn.com/w80/us-sc.png',
  'South Dakota': 'https://flagcdn.com/w80/us-sd.png',
  'Tennessee': 'https://flagcdn.com/w80/us-tn.png',
  'Texas': 'https://flagcdn.com/w80/us-tx.png',
  'Utah': 'https://flagcdn.com/w80/us-ut.png',
  'Vermont': 'https://flagcdn.com/w80/us-vt.png',
  'Virginia': 'https://flagcdn.com/w80/us-va.png',
  'Washington': 'https://flagcdn.com/w80/us-wa.png',
  'West Virginia': 'https://flagcdn.com/w80/us-wv.png',
  'Wisconsin': 'https://flagcdn.com/w80/us-wi.png',
  'Wyoming': 'https://flagcdn.com/w80/us-wy.png'
};

export default stateFlagsData;
